apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-quiz-app
  template:
    metadata:
      labels:
        app: cloud-quiz-app
    spec:
      containers:
      - name: quiz
        image: zskysy/cloud-quiz-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-quiz-app
spec:
  type: NodePort
  selector:
    app: cloud-quiz-app
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: cloud-quiz-app
