name: Auto Deploy React on S3

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      process.env.CI : false
      REACT_APP_REST_URL: ${{ secrets.REACT_APP_REST_URL }}
      REACT_APP_AUTH_USER_POOL_ID: ${{ secrets.REACT_APP_AUTH_USER_POOL_ID }}
      REACT_APP_AUTH_USER_POOL_WEB_CLIENT_ID: ${{ secrets.REACT_APP_AUTH_USER_POOL_WEB_CLIENT_ID }}
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build
        run: yarn build
        
      - name: Deploy to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-1
          aws s3 sync build/ s3://cloud-quiz-app/